# Generated by Django 3.2.3 on 2021-07-22 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSearch',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('fullDescription', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stockQuantity', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, null=True)),
                ('oldPrice', models.FloatField(blank=True, null=True)),
                ('sizeGuideUrl', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.CharField(blank=True, max_length=300, null=True)),
                ('picture', models.CharField(blank=True, max_length=100, null=True)),
                ('sizes', models.JSONField(null=True)),
                ('pictures', models.JSONField(null=True)),
                ('createdOnUtc', models.DateTimeField(verbose_name='date published')),
                ('updatedOnUtc', models.DateTimeField(verbose_name='date updated')),
                ('artikelNr1', models.IntegerField(blank=True)),
                ('artikelNr2', models.SmallIntegerField(blank=True, null=True)),
                ('statusCode', models.IntegerField(blank=True, null=True)),
                ('statusText', models.CharField(blank=True, max_length=50, null=True)),
                ('saisonRetourenCode', models.SmallIntegerField(blank=True, null=True)),
                ('saisonRetourenText', models.CharField(blank=True, max_length=50, null=True)),
                ('saisonCode', models.SmallIntegerField(blank=True, null=True)),
                ('saisonText', models.CharField(blank=True, max_length=50, null=True)),
                ('geschlechtCode', models.SmallIntegerField(blank=True, null=True)),
                ('geschlechtText', models.TextField(blank=True, null=True)),
                ('rayonCode', models.SmallIntegerField(blank=True, null=True)),
                ('rayonText', models.CharField(blank=True, max_length=50, null=True)),
                ('warenArtCode', models.IntegerField(blank=True, null=True)),
                ('warenArtText', models.CharField(blank=True, max_length=50, null=True)),
                ('wuCode', models.SmallIntegerField(blank=True, null=True)),
                ('wuText', models.TextField(blank=True, null=True)),
                ('waCode', models.SmallIntegerField(blank=True, null=True)),
                ('warenGruppe', models.CharField(blank=True, max_length=50, null=True)),
                ('alterCode', models.IntegerField(blank=True, null=True)),
                ('farbe', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('bezeichnung', models.TextField(blank=True, null=True)),
                ('pictureName', models.TextField(blank=True, null=True)),
                ('picturePathLocal', models.CharField(blank=True, max_length=50, null=True)),
                ('kollektion', models.TextField(blank=True, null=True)),
                ('comCode', models.TextField(blank=True, null=True)),
                ('lieferant', models.TextField(blank=True, null=True)),
                ('eKchf', models.FloatField(blank=True, null=True)),
                ('eti', models.FloatField(blank=True, null=True)),
                ('vp', models.FloatField(blank=True, null=True)),
                ('groessenCode', models.SmallIntegerField(blank=True, null=True)),
                ('groessen', models.JSONField(null=True)),
                ('zlQty', models.SmallIntegerField(blank=True, null=True)),
                ('categories', models.JSONField(null=True)),
                ('flag', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
