# Generated by Django 3.2.3 on 2021-07-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_alter_recommendation_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='StatusCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='categories',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='groessen',
            field=models.JSONField(null=True),
        ),
    ]
