# Generated by Django 3.2.3 on 2021-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110011_alter_recommendation_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='pictures',
            field=models.JSONField(null=True),
        ),
    ]
