# Generated by Django 3.2.3 on 2021-07-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110015_auto_20210707_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
