# Generated by Django 3.2.3 on 2021-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110012_recommendation_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='bezeichnung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
