# Generated by Django 3.2.3 on 2021-06-30 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('artikelNr1', models.IntegerField(blank=True)),
                ('artikelNr2', models.SmallIntegerField(blank=True, null=True)),
                ('StatusCode', models.CharField(blank=True, max_length=50, null=True)),
                ('statusText', models.CharField(blank=True, max_length=50, null=True)),
                ('SaisonRetourenCode', models.SmallIntegerField(blank=True, null=True)),
                ('saisonRetourenText', models.CharField(blank=True, max_length=50, null=True)),
                ('saisonCode', models.SmallIntegerField(blank=True, null=True)),
                ('saisonText', models.CharField(blank=True, max_length=50, null=True)),
                ('geschlechtCode', models.SmallIntegerField(blank=True, null=True)),
                ('geschlechtText', models.CharField(blank=True, max_length=50, null=True)),
                ('RayonCode', models.SmallIntegerField(blank=True, null=True)),
                ('rayonText', models.CharField(blank=True, max_length=50, null=True)),
                ('warenArtCode', models.IntegerField(blank=True, null=True)),
                ('warenArtText', models.CharField(blank=True, max_length=50, null=True)),
                ('wuCode', models.SmallIntegerField(blank=True, null=True)),
                ('wuText', models.CharField(blank=True, max_length=50, null=True)),
                ('waCode', models.SmallIntegerField(blank=True, null=True)),
                ('warenGruppe', models.CharField(blank=True, max_length=50, null=True)),
                ('alterCode', models.IntegerField(blank=True, null=True)),
                ('farbe', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('bezeichnung', models.CharField(blank=True, max_length=50, null=True)),
                ('pictureName', models.CharField(blank=True, max_length=50, null=True)),
                ('picturePathLocal', models.CharField(blank=True, max_length=50, null=True)),
                ('kollektion', models.CharField(blank=True, max_length=50, null=True)),
                ('comCode', models.CharField(blank=True, max_length=50, null=True)),
                ('lieferant', models.CharField(blank=True, max_length=50, null=True)),
                ('eKchf', models.FloatField(blank=True, null=True)),
                ('eti', models.FloatField(blank=True, null=True)),
                ('vp', models.FloatField(blank=True, null=True)),
                ('groessenCode', models.SmallIntegerField(blank=True, null=True)),
                ('groessen', models.TextField(blank=True, null=True)),
                ('zlQty', models.SmallIntegerField(blank=True)),
                ('productId', models.IntegerField(blank=True)),
                ('published', models.CharField(blank=True, max_length=10, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('productName', models.CharField(blank=True, max_length=50, null=True)),
                ('shortDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('fullDescription', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=10, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
