# Generated by Django 3.2.3 on 2021-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_recommendation_groessen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='categories',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
    ]
