# Generated by Django 3.2.3 on 2021-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20210706_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='published',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
