# Generated by Django 3.2.3 on 2021-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110014_auto_20210707_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='flag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='pictureName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
