# Generated by Django 3.2.3 on 2021-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110010_auto_20210707_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
