# Generated by Django 3.2.3 on 2021-07-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110016_alter_recommendation_bezeichnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='fullDescription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
