# Generated by Django 3.2.3 on 2021-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110013_alter_recommendation_bezeichnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='comCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='kollektion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='lieferant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='productName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
