# Generated by Django 3.2.3 on 2021-07-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '110017_alter_recommendation_fulldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='bezeichnung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='fullDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='geschlechtText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='wuText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
