# Generated by Django 3.2.3 on 2021-07-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_auto_20210707_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='RayonCode',
            new_name='rayonCode',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='SaisonRetourenCode',
            new_name='saisonRetourenCode',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='StatusCode',
            new_name='statusCode',
        ),
    ]
